### ISSUE TITLE
Can't add user to a team

### ISSUE THREAD

**Issue by shiroyasha** [renderedtext/cli#108]
![screen shot 2017-08-24 at 5 17 27 pm](https://user-images.githubusercontent.com/1779493/29673686-42adcbf0-88f0-11e7-8ff8-d84ba175dbf8.png)

**Comment by ijovan** [comment]
I've found the issue. It's a tricky one, and it's related to listing org members.
In the adding/removing members I can bypass the issue, but the issue still remains with the listing of members.

If I list all the users directly through the org, I won't see their permission levels.

I can list all the teams that belong to the org, and then determine the permission levels of their users. This is how it's currently implemented.

Now, the problem is that I don't see all the teams. Therefore, with this implementation:
1) I don't see the users that are in the org but not in the teams that I see
2) The permissions I see might not even be correct, since it is possible that I don't see all the teams (and thus all permissions)
